# Site settings
course_name: CSE 101 - Computer Science Principles
course_description: "Introduces central ideas of computing and computer science, instills practices of algorithmic and computational thinking, and engages students in the creative aspects of the field. Also introduces appropriate computing technology as a means for solving computational problems and exploring creative endeavors. Includes weekly computer programming assignments, but assumes no previous programming experience."
course_semester: "Spring 2023"

baseurl: "/suny-cse101" # the subpath of your site, e.g. /blog/
url: "http://rameau-fr.github.io/" # the base hostname & protocol for your site

schoolname: "SUNY Korea"
schoolurl: "https://www.sunykorea.ac.kr/en/"
twitter_username: Frameau89 

address: |
   SUNY Korea
   119-2 Songdomunhwa-Ro, Yeonsu-gu
   Incheon, Republic of Korea (21985)

# Set your Google Analytics tracking ID (set up yours at http://www.google.com/analytics/)
# google_analytics: UA-XXXXXXXX-X

### Do not change the followings unless you know what you are doing ###

# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
excerpt_separator: "<!--more-->"

include: ['_images', '_css']
exclude: ['develop']

dateformat: "%m/%d/%Y"

future: true
collections:
    events:
        output: true
    lectures:
        output: true
    assignments:
        output: true
    announcements:
        output: false


defaults:
  - scope:
      path: ""
      type: "assignments"
    values:
      layout: "assignment"
